name: Add new link
description: Request adding a new link to the website
title: "[Add]: "
labels: ["add link"]
assignees:
  - dreth
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for contributing with DeFi⚓Navy!

        ### Links HOWTO

        **You can use our [link formatting tool](http://defi.navy/linktool/)**
        
        To add any links, do so in the following format:

        ```md
        - [link label](https://link_content.com){:target="_blank"}
        ```
  - type: dropdown
    id: section
    attributes:
      label: Section to add the link to
      description: Under what website section should this be added
      options:
        - dApps - Decentralized Exchanges
        - dApps - Lending protocols
        - dApps - Assets
        - dApps - Indexes
        - dApps - Insurance
        - dApps - Options
        - dApps - Staking protocols
        - dApps - Yield farming protocols
        - dApps - Domains
        - dApps - NFTs
        - Communities - Reddit
        - Communities - Other sites
        - Utilities - Block explorers
        - Utilities - Development
        - Utilities - Crypto jobs
        - Utilities - Miscellaneous useful sites
        - Utilities - Airdrops
        - Utilities - Price tracking sites
        - Utilities - Wallets
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Link(s) to add
      description: Remember to add links formatted as markdown links as explained above
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Is this a duplicate?
      description: By submitting this issue, you declare that you have read, searched or checked through the issues page before submitting it.
      options:
        - label: Yes, my submission is not duplicated
          required: true
