name: Bug Report
description: File a bug report
title: "[Add link]: Project, project names or "Miscellaneous""
labels: ["add link"]
assignees:
  - dreth
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing with DeFi⚓Navy!
        
        To add any links, do so in the following format:

        ```md
        - [link label](https://link_content.com){:target="_blank"}
        ```

        If you want to add multiple links, just write them one under the other:

        ```md
        - [link label1](https://link_content1.com){:target="_blank"}
        - [link label2](https://link_content2.com){:target="_blank"}
        ```
  - type: dropdown
    id: section
    attributes:
      label: Section
      description: Under what website section should this be added
      options:
        - dApps - Decentralized Exchanges
        - dApps - Lending protocols
        - dApps - Assets
        - dApps - Indexes
        - dApps - Insurance
        - dApps - Options
        - dApps - Staking protocols
        - dApps - Yield farming protocols
        - dApps - Domains
        - dApps - NFTs
        - Communities - Reddit
        - Communities - Other sites
        - Utilities - Block explorers
        - Utilities - Development
        - Utilities - Crypto jobs
        - Utilities - Miscellaneous useful sites
        - Utilities - Price tracking sites
        - Utilities - Wallets
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: I know how to read
      description: By submitting this issue, you declare that you have read, searched or checked through the issues page before submitting it.
      options:
        - label: Yes, my submission is not duplicated
          required: true
