name: Modify existing link
description: Request modifying an existing link already present on the website
title: "[Modify]: "
labels: ["modify or update link"]
assignees:
  - dreth
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for contributing with DeFi⚓Navy!

        ### Links HOWTO

        **You can use our [link formatting tool](http://defi.navy/linktool/)**
        
        To modify any links, do so in the following format:

        ```md
        - [link label](https://link_content.com){:target="_blank"}
        ```
  - type: dropdown
    id: section
    attributes:
      label: Section where the link is located
      description: Under what website section is this link, so we can find it and fix it
      options:
        - dApps - Decentralized Exchanges
        - dApps - Lending protocols
        - dApps - CDP
        - dApps - Yield
        - dApps - Indexes
        - dApps - Liquid staking
        - dApps - Insurance
        - dApps - Dashboards
        - dApps - Bridges
        - dApps - Options
        - dApps - Derivatives
        - dApps - Staking
        - dApps - Stablecoins
        - dApps - Domains
        - dApps - NFTs
        - dApps - Services
        - dApps - Ohm forks and stuff
        - dApps - Others
        - Communities - Reddit
        - Communities - Other sites
        - Utilities - Block explorers
        - Utilities - Ethereum metrics
        - Utilities - Development
        - Utilities - Crypto jobs
        - Utilities - Miscellaneous useful sites
        - Utilities - Airdrops
        - Utilities - Price tracking sites
        - Utilities - Wallets
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Modified link(s)
      description: Remember to add links formatted as markdown links as explained above
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Is this a duplicate?
      description: By submitting this issue, you declare that you have read, searched or checked through the issues page before submitting it.
      options:
        - label: Yes, my submission is not duplicated
          required: true
